# Generated by Django 5.2.4 on 2025-08-03 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='チーム名')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='役職名')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('first_name', models.CharField(max_length=20, verbose_name='名')),
                ('last_name', models.CharField(max_length=20, verbose_name='性')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('employ_date', models.DateField(verbose_name='入社日')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='memberMng.group', verbose_name='チーム')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='memberMng.position', verbose_name='役職')),
            ],
        ),
    ]
