# Generated by Django 5.2.4 on 2025-08-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberMng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='チーム名'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='性'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='役職名'),
        ),
    ]
